const ATTENDANCE_CONFIG = {
    SHIFT_START_HOUR: 8,
    SHIFT_START_MINUTE: 30,
    SHIFT_END_HOUR: 17,
    SHIFT_END_MINUTE: 30,
  
    HALF_DAY_MINUTES: 240,

    OT_INCREMENT:30,
};

module.exports = ATTENDANCE_CONFIG;